#!/bin/bash
#
# Fix Workflow 78 Node Dependencies
# This script provides instructions and attempts to fix node dependencies
#

WORKFLOW_ID=78
AAP_URL="https://sc-awx.r53.infiniteranges.com"
AAP_USER="admin"
AAP_PASSWORD="IV1fD5JwqGJVuz4FjefWZKngVQNNpicg"

echo "🔧 Fixing Workflow 78 Node Dependencies"
echo "======================================================================"
echo ""
echo "⚠️  Note: Workflow node dependencies are best configured via AAP UI"
echo "   The API may not properly set up convergence rules."
echo ""
echo "📋 Correct Workflow Structure:"
echo ""
echo "   START"
echo "     ↓"
echo "   clone-repo"
echo "     ↓"
echo "   ┌─────────────┐"
echo "   ↓             ↓"
echo "   install    create-config"
echo "   └─────┬───────┘"
echo "         ↓ (converge)"
echo "      terraform-plan"
echo "         ↓"
echo "      terraform-apply"
echo "         ↓"
echo "      apply-callback"
echo ""
echo "🔗 Configure in AAP UI:"
echo "   ${AAP_URL}/#/templates/workflow_job_template/${WORKFLOW_ID}/visualizer"
echo ""
echo "📋 Steps:"
echo "   1. Open workflow visualizer"
echo "   2. Delete all node connections"
echo "   3. Connect nodes in this order:"
echo "      - START → clone-repo"
echo "      - clone-repo → install-terraform"
echo "      - clone-repo → create-config"
echo "      - install-terraform → terraform-plan"
echo "      - create-config → terraform-plan (set convergence: ALL)"
echo "      - terraform-plan → terraform-apply"
echo "      - terraform-apply → apply-callback"
echo ""
echo "💡 The convergence rule ensures terraform-plan waits for BOTH"
echo "   install-terraform AND create-config to complete."
